name: Deploy
on:
  push:
    branches: [ main ]  # o master, según tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install Dependencies
        run: yarn
          
      - name: Push Schema Changes
        run: npx prisma db push
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
