name: Monthly Preventive Tasks
on:
  schedule:
    - cron: '0 0 1 * *'  # Primer día de cada mes
  workflow_dispatch:  # Permite ejecución manual

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        run: |
          curl -X POST https://ransys.vercel.app/api/cron/generate-preventive-tasks \
          -H "Authorization: ${{ secrets.CRON_SECRET }}"
